# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'

group :test do
  gem 'rack-test', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
end
