apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: language-nexus
  template:
    metadata:
      labels:
        app: language-nexus
    spec:
      containers:
        - name: nexus
          image: dreadarceus/ln-nexus
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ln-ports
        - name: typescript
          image: dreadarceus/ln-typescript
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ln-ports
                  key: TYPESCRIPT_PORT
        - name: python
          image: dreadarceus/ln-python
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ln-ports
                  key: PYTHON_PORT
        - name: ruby
          image: dreadarceus/ln-ruby
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ln-ports
                  key: RUBY_PORT
        - name: go
          image: dreadarceus/ln-go
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ln-ports
                  key: GO_PORT
