apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: language-nexus
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000 # NEXUS_PORT
  type: LoadBalancer
