name: Nexus API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_test_and_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nexus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Build Docker image
        run: docker build -t dreadarceus/ln-nexus:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dreadarceus/ln-nexus:latest

      - name: Setup KinD
        uses: helm/kind-action@v1.4.0

      - name: Verify KinD setup
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Wait for pipelines to finish
        uses: lewagon/wait-on-check-action@v1.3.1
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          check-regexp: ^[a-z]+_pipeline$
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Start Deployment
        run: |
          kubectl apply -f ../k8s/ln-ports-configmap.yaml
          kubectl apply -f ../k8s/language-nexus-deployment.yaml
          kubectl apply -f ../k8s/nexus-service.yaml
          kubectl wait --for=condition=available --timeout=30s deployment/language-nexus

      - name: Forward port
        run: |
          kubectl port-forward service/nexus-service 4000:4000 &
          sleep 5

      - run: |
          curl -i http://localhost:4000/

      - name: Run Unit and Integration Tests
        run: yarn test

      - name: Fix coverage paths
        run: sed 's/SF:/SF:.\/nexus\//g' ./coverage/lcov.info > ./coverage/fixed_cov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./nexus
          files: ./nexus/coverage/fixed_cov.info
          name: codecov-umbrella
          fail_ci_if_error: true
