name: Nexus API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_test_and_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nexus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Build Docker image
        run: docker build -t dreadarceus/ln-nexus:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dreadarceus/ln-nexus:latest

      - name: Setup KinD
        uses: helm/kind-action@v1.4.0

      - name: Verify KinD setup
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Start Deployment
        run: |
          kubectl apply -f ../k8s/ln-ports-configmap.yaml
          kubectl apply -f ../k8s/language-nexus-deployment.yaml
          kubectl apply -f ../k8s/nexus-service.yaml
          kubectl wait --for=condition=available --timeout=30s deployment/language-nexus

      - name: Forward port
        run: |
          kubectl port-forward service/nexus-service 8080:80 &
          sleep 5

      - run: |
          curl -i http://localhost:8080/

      # - name: Integration Testing
      #   run: yarn test
