name: Python API CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "python/**"

jobs:
  py_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Lint code
        run: pylint **/*.py

      - name: Run tests
        run: coverage run --omit="./tests/**" -m pytest

      - name: Get coverage report
        run: coverage xml --skip-empty

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./python/coverage.xml
          name: codecov-umbrella
          flags: carry
          fail_ci_if_error: true

      - name: Build Docker image
        run: docker build -t dreadarceus/ln-python:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dreadarceus/ln-python:latest
