name: TypeScript API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "typescript/**"

jobs:
  lint_test_and_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Run tests
        run: yarn test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          root_dir: ./typescript
          files: ./typescript/coverage/lcov.info
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Build Docker image
        run: docker build -t dreadarceus/ln-ts:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push TypeScript API Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dreadarceus/ln-ts:latest
