name: TypeScript API CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "typescript/**"
  pull_request:
    branches:
      - main
    paths:
      - "typescript/**"

jobs:
  ts_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Run tests and get coverage
        run: yarn test

      - name: Fix coverage paths
        run: sed 's/SF:/SF:.\/typescript\//g' ./coverage/lcov.info > ./coverage/fixed_cov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./typescript
          files: ./typescript/coverage/fixed_cov.info
          name: codecov-umbrella
          flags: carry
          fail_ci_if_error: true

      - name: Build Docker image
        run: docker build -t dreadarceus/ln-typescript:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dreadarceus/ln-typescript:latest
